export const DEFAULT_ROLE_PERMISSIONS = {
  ROLE_LEVEL_1: ["*"],
  ROLE_LEVEL_2: ["USER.READ", "USER.CREATE", "SETTINGS.MANAGE"],
  ROLE_LEVEL_3: ["USER.READ", "REPORTS.EXPORT"],
  ROLE_LEVEL_4: ["USER.READ"],
  ROLE_LEVEL_5: ["USER.READ"],
};